[package]
name = "props-coin-wrapper"
version = "1.0.0"
authors = []

[addresses]
WrapperCoin="_"
property_test="0x6a56893e3834c1ede12623c83835c898b12ec5c481f8b3f62be8d75ce8dfd002"
fa_metadata="0xd9e99bdb67eb7af070cbfb89ae1bec20198b3fbd6d254d796a13bca20389faed"
admin_addr="0x8158281cfa125b7d71b00e379a112b1ae7e92b364a62ef80e1804a31d68c845c"
initial_creator_addr="0x8158281cfa125b7d71b00e379a112b1ae7e92b364a62ef80e1804a31d68c845c"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.HelloNFT]
git = "https://github.com/ariesgun/aptos-tokenize-props.git"
rev = "main"
subdir = "contract"

[dev-dependencies]
