[package]
name = "props-coin-wrapper"
version = "1.0.0"
authors = []

[addresses]
WrapperCoin="_"
tokenized_properties="0xdd8b2e087ab543aeda3dd1399f65c7f4705e985688d85c9627d2e7ee59876def"
fa_metadata="_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.TokenizedProperties]
git = "https://github.com/ariesgun/aptos-tokenize-props.git"
rev = "main"
subdir = "contract"

[dev-dependencies]
