[package]
name = "props-coin-wrapper"
version = "1.0.0"
authors = []

[addresses]
WrapperCoin="_"
property_test="0xc55af7fbf1923333ecc2368eaf5630daf4ae458a47477ec1ff835c7d2f3f3ec0"
fa_metadata="0x6AB028BA523D1511B0CFC7772CC4EFE9FE63A967C496D0C90CD93E0B342CE207"
admin_addr="0x8158281cfa125b7d71b00e379a112b1ae7e92b364a62ef80e1804a31d68c845c"
initial_creator_addr="0x8158281cfa125b7d71b00e379a112b1ae7e92b364a62ef80e1804a31d68c845c"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.HelloNFT]
git = "https://github.com/ariesgun/aptos-tokenize-props.git"
rev = "main"
subdir = "contract"

[dev-dependencies]
